### ISSUE TITLE
Need of a partslist

### ISSUE THREAD

**Issue by staffan-w** [BarneyMcgrew/BMG-Stop-Plate#9]
Its a great job you have done so far.
I would really like to build your project but it would be great to see a partslist, both for the stop-plate ang stop-plate-pro.
Also firmware for the stop-plate-pro.

Thank you for your great project, keep up the good work!

**Comment by ariusalipour** [comment]
Sorry for the lack of updated documentation. We hope to remedy this. As par request, the issue has been resolved.

[Complete Parts List](https://github.com/BarneyMcgrew/BMG-Stop-Plate/wiki/Complete-Parts-List)

**Comment by ariusalipour** [comment]
Apologies, the full parts list was not including the stop plate. We have remedied this!

**Comment by staffan-w** [comment]
Hello again!
Really good work with stopplate project.
Now I can really go ahead and follow your great instructions!

Just a question.
Have you ever thought of building a self setting target, like a popper or a
plate using similar hardware as the stopplate but with the edition of a
servo?

Thanks again for your great work!!

Den mån 16 maj 2022 21:07Aryan Alipour ***@***.***> skrev:
